import { db } from "@/lib/db";
import { NextResponse } from "next/server";

const products = [
  { name: 'iPhone 13 Pro', price: 999, desc: 'Latest Apple iPhone 13 Pro Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://rukminim2.flixcart.com/image/128/128/ktketu80/mobile/2/y/o/iphone-13-mlpk3hn-a-apple-original-imag6vpyur6hjngg.jpeg?q=70&crop=false' },
  { name: 'Sony WH-1000XM4', price: 349, desc: 'Sony WH-1000XM4 Wireless Noise-Canceling Headphones Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/51wPnvOs0cL._AC_UY218_.jpg' },
  { name: 'Google Pixel 6', price: 599, desc: 'Google Pixel 6 with Android 12 Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/e/y/n/pixel-8a-ga04432-in-google-original-imahyn3mqzdbzywg.jpeg?q=70' },
  { name: 'Apple Watch Series 7', price: 399, desc: 'Apple Watch Series 7 with GPS Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/s/q/r/-original-imagte6xkwbyutkk.jpeg?q=70' },
  { name: 'Samsung Galaxy Watch 4', price: 249, desc: 'Samsung Galaxy Watch 4 with Wear OS Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://rukminim2.flixcart.com/image/612/612/ksxjs7k0/smartwatch/v/s/t/android-sm-r890nzsainu-samsung-yes-original-imag6dtgqzdndppr.jpeg?q=70' },
  { name: 'MacBook Pro', price: 1299, desc: 'Apple MacBook Pro with M1 Chip Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/41DeT328kPL._AC_UY218_.jpg' },
  { name: 'Nintendo Switch', price: 299, desc: 'Nintendo Switch Console with Neon Blue and Red Joy-Con Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/412v5cSlP1L._SX38_SY50_CR,0,0,38,50_.jpg' },
  { name: 'Samsung Galaxy S21', price: 799, desc: 'Samsung Galaxy S21 with Android 11 Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71qeTVe5d1L._AC_UY218_.jpg' },
  { name: 'HP Spectre x360', price: 1199, desc: 'HP Spectre x360 Convertible Laptop Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71gqlzTfZzL._AC_UY218_.jpg' },
  { name: 'PlayStation 4 Pro', price: 399, desc: 'Sony PlayStation 4 Pro Console  Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/61loOpDhuML._AC_UY218_.jpg' },
  { name: 'Asus ROG', price: 1499, desc: 'Asus ROG Zephyrus Gaming Laptop Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/61h8kpNMqpL._AC_UY218_.jpg' },
  { name: 'Samsung Z-Flip 6', price: 1299, desc: 'it comes with a folded display Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71O5T+1IOpL._AC_UY218_.jpg' },
  { name: 'Fossil Gen 5', price: 295, desc: 'Fossil Gen 5 Smartwatch with Wear OS Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71Gtzq2yqnL._AC_UY218_.jpg' },
  { name: 'Lenovo ThinkPad X1', price: 1099, desc: 'Lenovo ThinkPad X1 Carbon Ultrabook Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71iGBUV2YPL._AC_UY218_.jpg' },
  { name: 'Fitbit Sense', price: 299, desc: 'Fitbit Sense with ECG and SpO2 Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/u/9/y/1-5-fb521bkgb-frcjk-android-ios-fitbit-yes-original-imagk952ujcccnmk.jpeg?q=70' },
  { name: 'Apple AirPods Pro', price: 249, desc: 'Apple AirPods Pro with Active Noise Cancellation Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71bhWgQK-cL._AC_UY218_.jpg' },
  { name: 'Jabra Elite 85h', price: 199, desc: 'Jabra Elite 85h Wireless Noise-Canceling Headphones Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/819iDDsPmWL._AC_UY218_.jpg' },
  { name: 'OnePlus 9', price: 729, desc: 'OnePlus 9 with Snapdragon 888 Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71xMs88FYbL._AC_UY218_.jpg' },
  { name: 'Sennheiser HD 450BT', price: 149, desc: 'Sennheiser HD 450BT Bluetooth 5.0 Wireless Headphone Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/71qPN6X0feL._AC_UY218_.jpg' },
  { name: 'Dell XPS 13', price: 999, desc: 'Dell XPS 13 with Intel Core i7 Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/61XxMkA7EAL._AC_UY218_.jpg' },
  { name: 'Xbox Series X', price: 499, desc: 'Microsoft Xbox Series X Console Lorem ipsum odor amet, consectetuer adipiscing elit. Nibh nullam gravida eros facilisis fringilla magnis egestas sapien. Gravida lectus porttitor curabitur, venenatis pharetra morbi. Viverra maecenas pretium purus facilisis dolor finibus. Vitae sagittis vel dui ad sit iaculis. Diam senectus sociosqu fringilla aenean cras. Sit lectus curae euismod nascetur; enim dui mus dolor. Quisque nam montes ad suscipit sociosqu rutrum dolor ultricies. Primis vestibulum congue finibus malesuada ante netus rutrum torquent molestie', image: 'https://m.media-amazon.com/images/I/51cN7sQ3aQL._AC_UY218_.jpg' },
];
export async function POST(_: Request) {
  try {

    for (const product of products) {
      await db.product.create({
        data: product
      });
    }

    console.log('30 products created!');
    return NextResponse.json({
      message: "products created"
    })
  } catch (err) {
    console.log(err);
    return new NextResponse("Internal Error", { status: 500 })
  }
}
